# Generated by Django 5.0.3 on 2024-09-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_campus', models.BooleanField(blank=True, null=True)),
                ('suite_style', models.BooleanField(default=False)),
                ('in_suite_bath', models.BooleanField(default=False)),
                ('desired_price', models.IntegerField()),
                ('utilities_included', models.BooleanField(default=False)),
                ('living_learning_community', models.JSONField(default=list)),
                ('ac', models.BooleanField(default=False)),
                ('public_transport', models.BooleanField(default=False)),
                ('desired_amenities', models.JSONField(default=list)),
                ('furnished', models.BooleanField(default=False)),
                ('desired_bedrooms', models.IntegerField()),
                ('desired_bathrooms', models.IntegerField()),
                ('desired_distance_from_campus', models.FloatField()),
                ('max_distance_from_campus', models.FloatField()),
                ('importance', models.JSONField()),
            ],
        ),
    ]
