# Generated by Django 5.0.3 on 2024-09-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_price', models.IntegerField(default=0)),
                ('utilities', models.BooleanField(default=False)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('amenities', models.JSONField(default=list)),
                ('public_transit', models.BooleanField(default=False)),
            ],
        ),
    ]
