# Generated by Django 5.0.3 on 2024-09-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='max_price',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='desired_price',
            field=models.IntegerField(default=0),
        ),
    ]
